INSERT INTO [tblForms] ([FieldID], [FormID], [FieldName], [FieldLabel], [FieldType], [FieldValue], [FieldValidation], [FieldDescription], [CustomAttributes], [FieldSortOrder], [CreatedDate], [ModifiedDate]) VALUES (1, 1, 'form_name', 'Contact Us Form', 'hidden', 'email', NULL, '<h2>Contact Us</h2><p>We are happy to hear from you! Send us your questions, comments, or feedback.</p>', 'simple', 0, '5/30/2007 9:06:15 AM', NULL);
INSERT INTO [tblForms] ([FieldID], [FormID], [FieldName], [FieldLabel], [FieldType], [FieldValue], [FieldValidation], [FieldDescription], [CustomAttributes], [FieldSortOrder], [CreatedDate], [ModifiedDate]) VALUES (2, 1, 'name', 'Name', 'text', NULL, 'required length:0,30', NULL, NULL, 1, '5/30/2007 9:06:55 AM', NULL);
INSERT INTO [tblForms] ([FieldID], [FormID], [FieldName], [FieldLabel], [FieldType], [FieldValue], [FieldValidation], [FieldDescription], [CustomAttributes], [FieldSortOrder], [CreatedDate], [ModifiedDate]) VALUES (3, 1, 'email', 'Email', 'text', NULL, 'required email', NULL, NULL, 2, '5/30/2007 9:11:03 AM', NULL);
INSERT INTO [tblForms] ([FieldID], [FormID], [FieldName], [FieldLabel], [FieldType], [FieldValue], [FieldValidation], [FieldDescription], [CustomAttributes], [FieldSortOrder], [CreatedDate], [ModifiedDate]) VALUES (4, 1, 'message', 'Message', 'textarea', NULL, 'required length:10,1000', NULL, 'rows="8"', 3, '5/30/2007 9:14:57 AM', NULL);
INSERT INTO [tblForms] ([FieldID], [FormID], [FieldName], [FieldLabel], [FieldType], [FieldValue], [FieldValidation], [FieldDescription], [CustomAttributes], [FieldSortOrder], [CreatedDate], [ModifiedDate]) VALUES (5, 1, 'submit', '&raquo; SUBMIT', 'submit', NULL, NULL, NULL, NULL, 4, '6/19/2007 4:53:46 PM', NULL);
INSERT INTO [tblForms] ([FieldID], [FormID], [FieldName], [FieldLabel], [FieldType], [FieldValue], [FieldValidation], [FieldDescription], [CustomAttributes], [FieldSortOrder], [CreatedDate], [ModifiedDate]) VALUES (7, 7, 'form_name', 'Form register', 'hidden', 'subscribe', NULL, '<h2>NEWSLETTER</h2><p>Enter your Email to subscribe to our newsletter.</p>', 'simple', 0, '7/19/2007 3:51:15 PM', NULL);
INSERT INTO [tblForms] ([FieldID], [FormID], [FieldName], [FieldLabel], [FieldType], [FieldValue], [FieldValidation], [FieldDescription], [CustomAttributes], [FieldSortOrder], [CreatedDate], [ModifiedDate]) VALUES (8, 7, 'mailaccount_r', 'Email', 'text', NULL, 'required email', NULL, NULL, 1, '7/19/2007 3:51:15 PM', NULL);
INSERT INTO [tblForms] ([FieldID], [FormID], [FieldName], [FieldLabel], [FieldType], [FieldValue], [FieldValidation], [FieldDescription], [CustomAttributes], [FieldSortOrder], [CreatedDate], [ModifiedDate]) VALUES (9, 7, 'submit', 'Subscribe', 'submit', NULL, 'ok1', '<a href="{SITEURL}/unsubcribe.asp" title="Click here to unsubscribe">Click here to Unsubscribe</a>', NULL, 3, '7/19/2007 3:51:15 PM', NULL);
INSERT INTO [tblForms] ([FieldID], [FormID], [FieldName], [FieldLabel], [FieldType], [FieldValue], [FieldValidation], [FieldDescription], [CustomAttributes], [FieldSortOrder], [CreatedDate], [ModifiedDate]) VALUES (10, 7, 'mailaccount2_r', 'Confirm Email', 'text', NULL, 'required email', NULL, 'onblur="requireConfirmation(this,document.getElementById(mailaccount_r.id))"', 2, '7/19/2007 3:51:15 PM', NULL);
INSERT INTO [tblForms] ([FieldID], [FormID], [FieldName], [FieldLabel], [FieldType], [FieldValue], [FieldValidation], [FieldDescription], [CustomAttributes], [FieldSortOrder], [CreatedDate], [ModifiedDate]) VALUES (11, 7, 'FBMLNAME', NULL, 'hidden', 'newsletter@example.com', NULL, NULL, NULL, 4, '7/19/2007 3:51:15 PM', NULL);
INSERT INTO [tblForms] ([FieldID], [FormID], [FieldName], [FieldLabel], [FieldType], [FieldValue], [FieldValidation], [FieldDescription], [CustomAttributes], [FieldSortOrder], [CreatedDate], [ModifiedDate]) VALUES (16, 7, 'subscribe_r', NULL, 'hidden', 'subscribe', NULL, NULL, 'checked="checked"', 9, '7/19/2007 3:51:15 PM', NULL);

INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (1, 'Company', 'Company Name', 'ASP VBScript CMS', 'text', 'required', 'Your company''s name. <strong>This setting is required.</strong>', 2, '2/21/2007 5:40:21 PM', '3/13/2007 7:49:07 PM');
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (2, 'General', 'Site Name', 'Content Management System on Classic ASP', 'text', 'required', 'Your website''s formal name, as it should be displayed in page headings and used throughout the website. <strong>This setting is required.</strong>', 1, '2/21/2007 5:40:29 PM', '7/3/2007 3:37:32 PM');
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (3, 'General', 'Site Shortname', 'VBScript CMS', 'text', NULL, 'If your Site Name is very long, you can specify an abbreviated or shortened form, which is preferrably used in specific places where space matters.', 4, '2/21/2007 5:40:36 PM', '7/3/2007 3:37:32 PM');
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (4, 'General', 'Site Title', 'ASP VBScript CMS', 'text', NULL, 'The website title appears in the title-bar window frame of your webbrowser. If left empty will use the <strong>Site Name</strong> variable.', 3, '2/21/2007 5:40:44 PM', '7/3/2007 3:37:32 PM');
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (5, 'General', 'Site Slogan', 'Download your free Classic ASP CMS today!', 'text', NULL, 'The site slogan is simply a "sub-heading" for your website. The slogan generally appears as a smaller-sized text along side the larger more emphasized ''Site Name''. Depending on your website''s layout, this may or may not appear in the Heading of each page and in customer email inquiries.', 2, '2/21/2007 5:41:05 PM', '7/3/2007 3:37:32 PM');
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (6, 'General', 'Site Keywords', 'classic asp cms content management system vbscript jscript asp3.0', 'textarea', 'simple', 'A comma separated list of general, site-wide keywords to be included in meta tags for every page in the site. Meta tags are visible to search engines.', 6, '2/21/2007 5:41:11 PM', '1/8/2007 8:41:48 PM');
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (7, 'General', 'Site Description', 'The worlds first true content management system written entirely on Classic ASP (VBScript).', 'textarea', 'simple', 'This description is included in meta tags for every page in the site. Meta tags are visible to search engines.', 5, '2/21/2007 5:41:21 PM', NULL);
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (8, 'Advanced', 'Default Page Encoding', 'iso-8859-1', 'text', 'required', 'Sets the default page encoding for your website. <strong>This setting is required.</strong><p class="alert">Advanced setting! Do not change unless you know what you are doing!</p>', 5, '2/21/2007 5:41:34 PM', NULL);
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (9, 'Advanced', 'Debug', '', 'checkbox', NULL, 'Permits extra website developer information to be displayed on the live site.  <p class="alert">Advanced setting! Do not change unless you know what you are doing!</p>', 3, '2/21/2007 5:41:45 PM', '11/17/2008 4:39:23 PM');
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (10, 'Advanced', 'Admin Email', 'webmaster@yourdomain.com', 'text', 'email', 'The email address of the person in charge of maintaining this site. This email will never be displayed on the website.', 4, '2/21/2007 5:42:02 PM', '7/19/2007 1:29:23 PM');
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (11, 'Company', 'Contact Email', 'asp-vbscript-cms@gmail.com', 'text', 'email', 'A general contact email address where all website form correspondence gets sent. Note: This may also be a comma-separated list of multiple email addresses.', 1, '2/21/2007 5:42:19 PM', '7/19/2007 1:29:23 PM');
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (12, 'Company', 'Contact Address1', '123 Main St.', 'text', NULL, 'The Company''s contact address. This will be displayed on the website''s contact page.', 3, '2/21/2007 5:42:26 PM', NULL);
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (13, 'Company', 'Contact Address2', 'Suite 101', 'text', NULL, NULL, 4, '2/21/2007 5:42:35 PM', NULL);
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (14, 'Company', 'Contact State', 'Anystate', 'text', 'state', 'The Company''s contact state. This will be displayed on the website''s contact page.', 6, '2/21/2007 5:42:42 PM', '10/16/2007 6:54:12 PM');
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (15, 'Company', 'Contact Zip', '12345', 'text', 'zip', 'The Company''s contact postal code. This will be displayed on the website''s contact page.', 7, '2/21/2007 5:43:56 PM', NULL);
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (16, 'Company', 'Contact Country', 'USA', 'text', 'country', 'The Company''s contact country. This will be displayed on the website''s contact page.', 8, '2/21/2007 5:44:03 PM', NULL);
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (17, 'Company', 'Contact Phone1', '800-123-4567', 'text', 'phone', 'The Company''s contact phone number. This will be displayed on the website''s contact page.', 9, '2/21/2007 5:44:12 PM', '6/11/2007 12:49:20 PM');
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (18, 'Company', 'Contact Phone2', '555-123-4567', 'text', 'phone', NULL, 10, '2/21/2007 5:44:29 PM', '6/11/2007 12:47:40 PM');
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (19, 'Company', 'Contact Fax', '555-123-4567', 'text', 'phone', 'The Company''s contact fax number. This will be displayed on the website''s contact page.', 11, '2/21/2007 5:44:34 PM', '6/11/2007 12:47:40 PM');
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (20, 'Company', 'Default Area Code', '555', 'text', 'number', 'The default area code is appended to a phone number when someone fills out a form on your website with a 7 digit number.', 12, '2/21/2007 6:00:21 PM', NULL);
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (21, 'Correspondence', 'Email Intro', 'The following customer inquiry was submitted online:', 'text', NULL, 'Text pre-pended to the content of all emails when someone sends in a feedback or submits a contact form on your website.', 2, '2/21/2007 6:06:21 PM', NULL);
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (22, 'Correspondence', 'Subjectline Prefix', '[{SHORTNAME} site]', 'text', NULL, 'The text pre-pended to the subjectline of all emails sent from your website.  Examples could be:  [{SITENAME}], [{SHORTNAME}}],({COMPANY}), :::Your Special Message Here:::', 1, '2/21/2007 6:10:12 PM', '3/13/2007 7:49:07 PM');
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (23, 'Correspondence', 'CC Sender', '1', 'checkbox', NULL, 'If enabled, then a copy of the feedback/contact form submission is Carbon Copied to the person who filled out the form.', 4, '2/21/2007 6:10:52 PM', '2/28/2007 10:49:54 AM');
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (25, 'Correspondence', 'Email Header Image', '{SITEURL}/images/mailheader.jpg', 'text', 'image', 'The absolute url to the image used as a header in Rich Text emails sent by your website. If left blank, no image will be used in email header', 3, '2/21/2007 6:16:24 PM', NULL);
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (26, 'General', 'Site Logo', '{SITEURL}/images/logo.gif', 'text', 'image', 'The absolute url to the image used as a logo on your website''s pages. If left blank, no image will be used and the <strong>Site Name</strong> and <strong>Slogan</strong> will be used in place of the logo at the top of each page.', 7, '2/21/2007 6:25:19 PM', '11/3/2007 2:27:07 PM');
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (27, 'Advanced', 'Enrich Form Widgets', '1', 'checkbox', NULL, 'Permits use of advanced form widgets from the <a href="http://dojotoolkit.org" title="click on the ''see it in action'' tab once you are there">Dojo framework</a> in place of regular form fields.', 2, '2/27/2007 2:26:21 PM', '10/18/2007 11:50:33 AM');
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (31, 'Advanced', 'SMTP Host', 'smtp.gmail.com', 'text', NULL, NULL, 6, '2/27/2007 10:18:06 PM', NULL);
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (32, 'General', 'Bookmark Icon', '{SITEURL}/favicon.ico', 'text', 'image', 'Also known as a "favicon",  this is the location of the image file that you will see in dirrection bar of the webbrowser as well as if you bookmark the website. The image file format typically has the file extension ".ico"', 8, '3/13/2007 9:48:11 PM', '3/13/2007 10:42:10 PM');
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (33, 'Advanced', 'Enabled Site', '1', 'checkbox', NULL, 'Caution: deselecting this checkbox will disable all public site interaction, only site administrators will have access to the admin section.', 1, '7/11/2007 1:18:21 PM', '11/7/2007 1:40:14 PM');
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (34, 'Company', 'Contact City', 'Anycity', 'text', NULL, 'The Company''s contact city. This will be displayed on the website''s contact page.', 5, '7/30/2007 5:45:08 PM', '10/16/2007 6:54:12 PM');
INSERT INTO [tblGlobalSettings] ([SettingId], [SettingCategory], [SettingName], [SettingValue], [ValueType], [ValidationRule], [SettingDescription], [SortOrder], [CreationDate], [ModifiedDate]) VALUES (35, 'Advanced', 'Google Analytics', 'UA-0000000-XX', 'text', 'number', 'The code setup when registering a new profile in <a href="http://google.com/analytics">Google Analytics</a>.', 7, '10/16/2007 6:56:17 PM', '10/16/2007 7:06:19 PM');

INSERT INTO [tblModules] ([ID], [Active], [Name], [Description], [Type], [StyleID], [StyleClass], [StyleInline], [PageIDs], [CustomSettings], [SortOrder], [Location]) VALUES (2, 1, 'What Our Customers Are Saying', 'Our clients testimonials.', 3, '', '', '', ':6:', '', 0, 'main');
INSERT INTO [tblModules] ([ID], [Active], [Name], [Description], [Type], [StyleID], [StyleClass], [StyleInline], [PageIDs], [CustomSettings], [SortOrder], [Location]) VALUES (3, 1, 'Feedback Form', 'Online contact form.', 1, '', '', '', ':2:', 'form_id{1}', 0, 'sub');

INSERT INTO [tblModuleTypes] ([Disabled], [ModID], [ModName], [ModHandler], [ModDescription]) VALUES (0, 1, 'Web Form', 'mod_form', 'A module for inserting a form into a page.');
INSERT INTO [tblModuleTypes] ([Disabled], [ModID], [ModName], [ModHandler], [ModDescription]) VALUES (1, 2, 'Links', 'mod_links', 'A list of website links, allowing a name, <abbr title="Uniform Resource Locator; the location of a file on the web (eg, http://www.xyz.com/file.htm)">URL</a>, and image.');
INSERT INTO [tblModuleTypes] ([Disabled], [ModID], [ModName], [ModHandler], [ModDescription]) VALUES (0, 3, 'Testimonials', 'mod_testimonials', 'A list of customer testimonials, allowing customer name, customer comments, location, and date.');
INSERT INTO [tblModuleTypes] ([Disabled], [ModID], [ModName], [ModHandler], [ModDescription]) VALUES (1, 4, 'Blog/Newsletter', 'mod_blog', 'A module for creating a blog or newsletter functionality; includes user/group administration and subscribe/unsubscribe functionality.');
INSERT INTO [tblModuleTypes] ([Disabled], [ModID], [ModName], [ModHandler], [ModDescription]) VALUES (0, 5, 'RSS Feed', 'mod_rss', 'A module for including the content of an RSS Feed on your site.');
INSERT INTO [tblModuleTypes] ([Disabled], [ModID], [ModName], [ModHandler], [ModDescription]) VALUES (1, 6, 'Poll', 'mod_poll', 'A module for creating and managing a poll.');
INSERT INTO [tblModuleTypes] ([Disabled], [ModID], [ModName], [ModHandler], [ModDescription]) VALUES (1, 7, 'Survey', 'mod_survey', 'A module for creating and managing a multi-step survey.');
INSERT INTO [tblModuleTypes] ([Disabled], [ModID], [ModName], [ModHandler], [ModDescription]) VALUES (0, 8, 'Products', 'mod_products', 'A module for displaying a product catalogue on your site.');
INSERT INTO [tblModuleTypes] ([Disabled], [ModID], [ModName], [ModHandler], [ModDescription]) VALUES (0, 9, 'Photo Gallery', 'mod_gallery', 'A module for displaying an image gallery on your site.');
INSERT INTO [tblModuleTypes] ([Disabled], [ModID], [ModName], [ModHandler], [ModDescription]) VALUES (0, 10, 'Random Content', 'mod_random_content', 'A module for selecting and displaying a random piece of content (currently only page content) from the database.');
INSERT INTO [tblModuleTypes] ([Disabled], [ModID], [ModName], [ModHandler], [ModDescription]) VALUES (0, 11, 'Product Categories', 'mod_prod_categories', 'A module for listing product categories');
INSERT INTO [tblModuleTypes] ([Disabled], [ModID], [ModName], [ModHandler], [ModDescription]) VALUES (0, 12, 'HTML Snippet', 'mod_html_snippet', 'A module for adding a snippet of HTML code to a page in your site.');
INSERT INTO [tblModuleTypes] ([Disabled], [ModID], [ModName], [ModHandler], [ModDescription]) VALUES (0, 13, 'Banner Image', 'mod_banner', 'A module for displaying a banner on your site.');

INSERT INTO [tblPageContent] ([ContentID], [PageID], [PageContent], [ModifiedDate]) VALUES (1, 1, '<h1>Welcome to {SITENAME}</h1>
{BOILERPLATE_WARNING}

{BOILERPLATE_CONTENT}', '2/8/2007 11:53:46 AM');
INSERT INTO [tblPageContent] ([ContentID], [PageID], [PageContent], [ModifiedDate]) VALUES (2, 3, '<h1>About {SITENAME}</h1>
{BOILERPLATE_WARNING}', '2/22/2007 8:43:59 PM');
INSERT INTO [tblPageContent] ([ContentID], [PageID], [PageContent], [ModifiedDate]) VALUES (3, 2, '<h1>Contact Information</h1><p>{Contact Address1}<br>{Contact Address2}<br>{Contact City}, {Contact State} {Contact Zip}<br></p><h3>Phone:</h3> 
<p>{Contact Phone1} Toll Free<br>{Contact Phone2} Local<br>{Contact Fax} Fax<br></p><h3>Business Hours:</h3>', '3/9/2007 5:58:16 PM');
INSERT INTO [tblPageContent] ([ContentID], [PageID], [PageContent], [ModifiedDate]) VALUES (4, 6, '<h1>What Our Customers Are Saying</h1>', '5/29/2007 9:01:10 PM');

INSERT INTO [tblPages] ([PageID], [Active], [PageName], [PageFileName], [PageLinkHoverText], [PageDescription], [PageKeywords], [MainMenu], [PageTitle], [MenuIndex], [ParentPage], [Style], [CreateDate]) VALUES (1, 1, 'Home', 'default.asp', 'Welcome to {SITENAME}', '', '', 1, 'Classic ASP Content Management System for Quick & Easy Web Design.', 1, 0, 'main', '1/10/2007 2:44:23 PM');
INSERT INTO [tblPages] ([PageID], [Active], [PageName], [PageFileName], [PageLinkHoverText], [PageDescription], [PageKeywords], [MainMenu], [PageTitle], [MenuIndex], [ParentPage], [Style], [CreateDate]) VALUES (2, 1, 'Contact Us', 'contact.asp', '', '', '', 1, 'Contact Us', 4, 0, 'main-2col', '1/10/2007 2:44:55 PM');
INSERT INTO [tblPages] ([PageID], [Active], [PageName], [PageFileName], [PageLinkHoverText], [PageDescription], [PageKeywords], [MainMenu], [PageTitle], [MenuIndex], [ParentPage], [Style], [CreateDate]) VALUES (3, 1, 'About', 'about.asp', '', '', '', 1, 'About', 2, 0, 'main', '1/10/2007 2:45:58 PM');
INSERT INTO [tblPages] ([PageID], [Active], [PageName], [PageFileName], [PageLinkHoverText], [PageDescription], [PageKeywords], [MainMenu], [PageTitle], [MenuIndex], [ParentPage], [Style], [CreateDate]) VALUES (4, 1, 'Terms of Service', 'legal/terms.asp', '', '', '', 0, 'Terms of Service', 999, 0, 'main', '1/11/2007 5:51:54 PM');
INSERT INTO [tblPages] ([PageID], [Active], [PageName], [PageFileName], [PageLinkHoverText], [PageDescription], [PageKeywords], [MainMenu], [PageTitle], [MenuIndex], [ParentPage], [Style], [CreateDate]) VALUES (5, 1, 'Privacy Policy', 'legal/privacy.asp', '', '', '', 0, 'Privacy Policy', 999, 0, 'main', '1/12/2007 12:08:54 PM');
INSERT INTO [tblPages] ([PageID], [Active], [PageName], [PageFileName], [PageLinkHoverText], [PageDescription], [PageKeywords], [MainMenu], [PageTitle], [MenuIndex], [ParentPage], [Style], [CreateDate]) VALUES (6, 1, 'Testimonials', 'testimonials.asp', '', '', '', 1, 'What Our Customers Are Saying', 3, 0, 'main', '10/15/2007 11:31:37 AM');

INSERT INTO [tblTestimonials] ([ID], [Active], [Name], [Email], [ShowEmail], [SortOrder], [Comments], [Location], [TestimonialDate], [Timestamp]) VALUES (16, 1, 'Cicero', 'cicero@lipsum.org', 1, 0, 'Sed nec dui. Aliquam erat volutpat. Nam a dui eu mi gravida ultricies. Mauris consequat lorem eu neque. Suspendisse nisi nisl, congue a, facilisis quis, pellentesque sed, massa. ', 'Nam a dui eu mi gravida ultricies. ', '1/1/2007', '8/9/2007 12:03:55 PM');
INSERT INTO [tblTestimonials] ([ID], [Active], [Name], [Email], [ShowEmail], [SortOrder], [Comments], [Location], [TestimonialDate], [Timestamp]) VALUES (17, 1, 'Cicero', 'cicero@lipsum.org', 1, 1, 'Sed nec dui. Aliquam erat volutpat. Nam a dui eu mi gravida ultricies. Mauris consequat lorem eu neque. Suspendisse nisi nisl, congue a, facilisis quis, pellentesque sed, massa.', 'de Finibus Bonorum et Malorum, 45 BC', '1/1/2007', '10/18/2007 10:57:25 AM');

INSERT INTO [tblUserRoles] ([id], [Name], [Description], [Level]) VALUES (1, 'Administrator', 'Administrators have access to all site settings and can create,modify, and delete content.', 100);
INSERT INTO [tblUserRoles] ([id], [Name], [Description], [Level]) VALUES (2, 'Manager', 'Managers have access to most site settings and can create, modify, and delete content', 80);
INSERT INTO [tblUserRoles] ([id], [Name], [Description], [Level]) VALUES (3, 'Editor', 'Editors have limited access to administration and may only create and modify content.', 40);
INSERT INTO [tblUserRoles] ([id], [Name], [Description], [Level]) VALUES (4, 'Registered', 'Registered users may only modify their own account settings.  They cannot log into the site administration.', 20);

INSERT INTO [tblUsers] ([id], [UserID], [Password], [LastLogin], [Disabled], [Description], [FirstName], [SecondName], [Email], [Phone], [Address1], [Address2], [City], [State], [PostalCode], [Country], [Role]) VALUES (1, 'admin', 'password', '11/8/2010', 0, NULL, 'Site', 'Administrator', 'webmaster@example.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 100);
